### ISSUE TITLE
Admin > Add Class > Add Same Class twice 

### ISSUE THREAD

**Issue by ParasRawat** [MontbitTech/WebApp-e-EdPort-LMS#174] opened 2020-08-01 10:19 UTC
Steps:
1. Log in as admin
2. Add a class in the classes tab 
3. Try to add the same class again

Actual: Duplicated classes are created in the lms as well google classroom
Expected: Only one instance of each class should be created in the lms and classroom

![bug](https://user-images.githubusercontent.com/33607689/89099618-55a92300-d40e-11ea-95b7-804def8fd7fb.PNG)
![image](https://user-images.githubusercontent.com/33607689/89099651-8db06600-d40e-11ea-83c3-1e1f5e52fd10.png)

**Comment by Anshumanshrivastava** [comment] 2020-08-04 08:16
cannot reproduce

**Comment by ChitraQA** [comment] 2020-08-06 15:21
Getting appropriate error and Duplicate class is not created. 
Tested and closed in 0508

**Closed by ChitraQA** 2020-08-06 15:21 UTC
Labels: Critical, bug
